import random
from entropy_utils import EntropyEngine, GRID_SIZE, SHIP_LENGTH, NUM_SHIPS

class BattleshipGame:
    # For managing the actual gameplay, processing guesses against the secret board.
    def __init__(self, ai_engine):
        # We pick one secret board from the valid list generated by the program.
        # This I made to ensure the game is always solvable.
        if not ai_engine.all_valid_boards:
            raise ValueError("No valid boards generated!")
            
        self.secret_board = random.choice(ai_engine.all_valid_boards)
        self.played_moves = set()
        self.total_hits = 0
        self.max_hits = NUM_SHIPS * SHIP_LENGTH

    def process_guess(self, r, c):
        """
        For checking a coordinate against the secret board.
        Returns: True (Hit) or False (Miss)
        """
        if (r, c) in self.played_moves:
            raise ValueError("You already guessed that coordinate.")
            
        self.played_moves.add((r, c))
        
        if (r, c) in self.secret_board:
            self.total_hits += 1
            return True
        return False

    def is_game_over(self):
        return self.total_hits == self.max_hits